#!/usr/bin/env julia
# Write db/precompile_fixture.sql: the newest few rows of every table of a
# real database, as INSERT statements. The package's precompile workload
# loads them into an in-memory database and renders every route, so the
# server starts with its code compiled for the row types the real data
# has (an empty table gives a SQL expression no type at all).
#
#   julia --project db/make_fixture.jl --db ci-timing.sqlite [--rows 5]
#
# Run it again when a table or column is added to schema.sql.

using Pkg
Pkg.activate(dirname(@__DIR__); io=devnull)
using SQLite, DBInterface

const OUT = joinpath(@__DIR__, "precompile_fixture.sql")

function literal(v)
    v === missing && return "NULL"
    # One statement per line: a newline inside a value becomes char(10)
    v isa AbstractString && return "'" * replace(v, "'" => "''", "\r" => "'||char(13)||'", "\n" => "'||char(10)||'") * "'"
    v isa Vector{UInt8} && return "X'" * bytes2hex(v) * "'"
    v isa AbstractFloat && return isfinite(v) ? repr(v) : "NULL"
    return string(v)
end

# Row insertion order is not time order: backfills append old reports after
# new ones. The newest rows are by a date column when the table or the
# parent it points to has one, else by rowid or the primary key.
const DATE_COLUMNS = ("date", "created_at", "build_created_at", "time", "started_at", "first_at", "last_seen")

function newest_order(db, t)
    columns(table) = [String(r.name) for r in DBInterface.execute(db, "SELECT name FROM pragma_table_info(?) ORDER BY cid", (table,))]
    datecol(table) = findfirst(in(columns(table)), DATE_COLUMNS)
    pk = [String(r.name) for r in DBInterface.execute(db, "SELECT name FROM pragma_table_info(?) WHERE pk > 0 ORDER BY pk", (t,))]
    rowid = isempty(collect(DBInterface.execute(db, "SELECT 1 FROM sqlite_master WHERE name = ? AND sql LIKE '%WITHOUT ROWID%'", (t,))))
    tie = rowid ? "rowid DESC" : join(["\"$c\" DESC" for c in pk], ", ")
    d = datecol(t)
    d === nothing || return "\"$(DATE_COLUMNS[d])\" DESC, $tie"
    for fk in SQLite.Tables.rowtable(DBInterface.execute(db, "SELECT \"table\" AS parent, \"from\" AS child_col, \"to\" AS parent_col FROM pragma_foreign_key_list(?)", (t,)))
        d = datecol(String(fk.parent))
        d === nothing && continue
        return "(SELECT \"$(DATE_COLUMNS[d])\" FROM \"$(fk.parent)\" WHERE \"$(fk.parent_col)\" = \"$t\".\"$(fk.child_col)\") DESC, $tie"
    end
    return tie
end

function write_rows(io, t, rows)
    isempty(rows) && return
    cols = join(["\"$c\"" for c in propertynames(rows[1])], ", ")
    for r in rows
        println(io, "INSERT OR IGNORE INTO \"$t\" ($cols) VALUES (", join([literal(getproperty(r, c)) for c in propertynames(r)], ", "), ");")
    end
end

function main(args)
    i = findfirst(==("--db"), args)
    path = i === nothing ? get(ENV, "CI_TIMING_DB", joinpath(dirname(@__DIR__), "ci-timing.sqlite")) : args[i+1]
    i = findfirst(==("--rows"), args)
    n = i === nothing ? 5 : parse(Int, args[i+1])
    db = SQLite.DB(path)
    # The raw_* tables hold the fetchers' compressed payloads, which no route reads
    tables = [String(r.name) for r in DBInterface.execute(db, "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE 'raw_%' ORDER BY name")]
    open(OUT, "w") do io
        println(io, "-- Generated by db/make_fixture.jl from $(basename(path)) on $(Dates.today()): the newest $n rows of every table.")
        println(io, "-- Loaded by the precompile workload in src/precompile.jl after schema.sql; do not edit by hand.")
        for t in tables
            order = newest_order(db, t)
            # Every meta row: the change sequences and the fetchers' cursors are keys
            limit = t == "meta" ? "" : " LIMIT $n"
            rows = SQLite.Tables.rowtable(DBInterface.execute(db, "SELECT * FROM \"$t\" ORDER BY $order$limit"))
            isempty(rows) && continue
            # Oldest first, so parents that are also rows here come before their children
            write_rows(io, t, reverse(rows))
            # The rows these reference, so the routes' joins find them
            for fk in SQLite.Tables.rowtable(DBInterface.execute(db, "SELECT \"table\" AS parent, \"from\" AS child_col, \"to\" AS parent_col FROM pragma_foreign_key_list(?)", (t,)))
                keys = unique(filter(!ismissing, [getproperty(r, Symbol(fk.child_col)) for r in rows]))
                isempty(keys) && continue
                marks = join(fill("?", length(keys)), ", ")
                parents = SQLite.Tables.rowtable(DBInterface.execute(db, "SELECT * FROM \"$(fk.parent)\" WHERE \"$(fk.parent_col)\" IN ($marks)", Tuple(keys)))
                write_rows(io, String(fk.parent), parents)
            end
        end
    end
    println("wrote $OUT ($(filesize(OUT)) bytes, $(length(tables)) tables)")
end

using Dates
main(ARGS)
